In [1]:
import numpy
import pandas

In [2]:
num_list = numpy.random.binomial(1, 0.5, (26, 4))
print num_list

[[0 1 0 0]
 [1 1 1 0]
 [0 1 1 1]
 [0 1 1 1]
 [1 1 1 0]
 [1 1 1 1]
 [1 0 1 0]
 [1 0 1 0]
 [1 1 0 0]
 [0 0 0 0]
 [1 0 1 0]
 [1 0 1 1]
 [0 1 0 0]
 [1 1 1 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 1 0 0]
 [0 0 1 0]
 [1 0 0 0]
 [0 1 0 0]
 [1 0 1 0]
 [0 1 0 1]
 [0 0 1 1]
 [1 1 0 0]
 [1 0 1 1]
 [1 0 1 0]]


In [3]:
#new_list = num_list[num_list>0.5]
new_list = num_list

In [4]:
df = pandas.DataFrame()
le = [unichr(i) for i in range(0x41, 0x5B, 1)]
columns = ['one', 'two', 'three', 'four']
df = pandas.DataFrame(new_list, index = le, columns = columns)
print df

   one  two  three  four
A    0    1      0     0
B    1    1      1     0
C    0    1      1     1
D    0    1      1     1
E    1    1      1     0
F    1    1      1     1
G    1    0      1     0
H    1    0      1     0
I    1    1      0     0
J    0    0      0     0
K    1    0      1     0
L    1    0      1     1
M    0    1      0     0
N    1    1      1     0
O    0    0      1     0
P    0    0      0     1
Q    0    1      0     0
R    0    0      1     0
S    1    0      0     0
T    0    1      0     0
U    1    0      1     0
V    0    1      0     1
W    0    0      1     1
X    1    1      0     0
Y    1    0      1     1
Z    1    0      1     0


In [5]:
df = df.sort_values("two",0,False)
df = df.iloc[:5]
print df

   one  two  three  four
A    0    1      0     0
I    1    1      0     0
X    1    1      0     0
V    0    1      0     1
T    0    1      0     0


In [6]:
cf = df['one']
print "sum      {}".format(cf.sum())
print cf.describe()

sum      2
count    5.000000
mean     0.400000
std      0.547723
min      0.000000
25%      0.000000
50%      0.000000
75%      1.000000
max      1.000000
Name: one, dtype: float64
